name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          docker build -t wavedays:1.0.0 .
      
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag wavedays:1.0.0 ${{ secrets.DOCKER_USERNAME }}/wavedays:1.0.0
          docker push ${{ secrets.DOCKER_USERNAME }}/wavedays:1.0.0

